### ISSUE TITLE
When deploying this, warning shows stating that ccouldn't connect to site cloud code is unavailable. What is this issue?

### ISSUE THREAD

**Issue by malcolm-dane** [parse-community/parse-server-example#407] opened 2021-11-27 06:59 UTC
I have cloud code defined in my cloud/functions.js, then a main with the require statement. Why does it keep giving this error? I have tried everything!!!! Do I need to just build this from the main api?

**Comment by dblythy** [comment] 2021-12-16 01:19
Parse Server attempts to perform a GET request on `${serverURL}/health` and if it fails, that response is logged.

The issue is more than likely related to your configuration.

[This might help you](https://github.com/parse-community/parse-server/issues/4506)

Closing as it doesn't seem to be a Parse Server / Parse Server Example issue.

Alternatively, feel free to post in our [community forum](https://community.parseplatform.org/) if the issue continues.

**Closed by dblythy** 2021-12-16 01:19 UTC
