### ISSUE TITLE
mLab has been shut down and Heroku addon is gone

### ISSUE THREAD

**Issue by mrharsh2804** [parse-community/parse-server-example#389] opened 2021-03-08 23:43 UTC
Would it be possible to add instructions for parse server example for MongoDB Atlas with Heroku instead of mLab since that is the closest alternative to mLab?

**Comment by mtrezza** [comment] 2021-03-11 00:36
Thank you for reporting. I'm closing this as it seems to be a duplicate of #387.
Let's continue the discussion there.

Feel free to comment if you think this is not a duplicate and we can re-open this issue.

**Closed by mtrezza** 2021-03-11 00:36 UTC
